language: node_js

node_js:
  - "node"

script:
  - npm run build
  - npm test

after_script:
  - bash bin/after_script.sh

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
    - gh-pages
